version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  # 생성할 데이터베이스 이름
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d  # 초기 SQL 스크립트를 포함한 폴더
    restart: unless-stopped

